import HeroImage from '../assets/images/hero-homepage.png'
import { Link } from 'react-router-dom'
import { ArrowIcon } from '../components/Icons'
import Resume from '../Resume.pdf'
// import About from './About'
import { AnimatedText } from '../components/AnimatedText'
import { Helmet } from 'react-helmet'
import TransitionEffect from '../components/TransitionEffect'
import { Layout } from '../components/Layout'
import lightBulb from '../assets/images/svgs/bulb.svg'
import HireMe from '../components/HireMe'

const Home = () => {
  
  return (
    <>

      <Helmet>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>

      <TransitionEffect />

      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <img
                src={HeroImage}
                alt='an excited developer'
                className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority="true"
                sizes='(max-widthL768px) 100vw,
                (max-width:1200px) 60vw,
                50vw'
              />
            </div>

            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text="Bringing Dreams to Life: Where Vision Meets Code and Design."
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center  lg:!text-6xl md:!text-6xl sm:!text-3xl'
              />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                With over 4 years of experience in software engineering, I cultivated strong expertise in multiple web based technologies in different industries in healthcare and insurance domains. I have extensive experience from building software to make them production ready. I worked on multiple projects from scratch to production. Along with the traditional web development I have also pitched in to Saas based technologies like Salesforce, and guidewire and understood their basic to advanced implementations in some of the previous projects. I am passionate about building software   that is scalable, maintainable and user friendly. I am always eager to learn new technologies and work on challenging projects.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link
                  to={Resume}
                  download={true}
                  target='blank'
                  className='flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base'
                >
                  Resume

                  <ArrowIcon className="w-5 ml-1" />
                </Link>

                <Link
                  to="/contactus"
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >
                  Contact
                </Link>
              </div>
            </div>

          </div>
          <HireMe />
          <div className='absolute right-8 bottom-0 inline-block w-24'>
            <img src={lightBulb} alt="Feecon" className='w-full h-auto md:hidden' />
          </div>
        </Layout>
      </main>
    </>
  )
}
export default Home