import { Helmet } from 'react-helmet'
import TransitionEffect from '../components/TransitionEffect'
import { Layout } from '../components/Layout'
const Project = () => {

  return (
    <>
      <Helmet>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>
      <TransitionEffect />
      <main className='text-center justify-center'>
        <Layout>
          <h1 className='dark:text-light'>Work in progress on this page!</h1>
        </Layout>

      </main>
    </>
  )
}

export default Project